language: ruby
rvm:
  - 2.2.2
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential freeglut3-dev libsdl-ttf2.0-dev libxinerama-dev libpango1.0-dev libgl1-mesa-dev libfreeimage-dev libopenal-dev libsndfile-dev
